zTuple = ('Mr. Ed', 'Miss Daisy', 'Mr. T', 'Dr. Who')
zList = (['Mr. Ed', 'Miss Daisy', 'Mr. T', 'Dr. Who'])
zSet = ({'Mr. Ed', 'Miss Daisy', 'Mr. T', 'Dr. Who'})
zDict = ({3: 'Mr. Ed', 2: 'Miss Daisy', 4: 'Mr. T', 1: 'Dr. Who'})
print(sorted(zTuple))
print(sorted(zList))
print(sorted(zSet))
print(sorted(zDict.items()))
